config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/songs', to: 'songs#index', as: "songs"
  devise_for :users
  resources :songs

  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :user
    validates :title, uniqueness: true
    validates :title, format: {with: /\A[A-Z]/, message: "first letter must be capitalized"}
    validates :artist, format: {with: /\A[A-Z]/, message: "first letter must be capitalized"}
    
end

app/models/user.rb
class User < ApplicationRecord
  has_many :songs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        songs_path #your path
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    before_action :set_song, only: [ :destroy, :edit, :update]
  def index
   @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def destroy
    @song.destroy
    redirect_to songs_path(@song)
end

  def new
    @songs = current_user.songs.new
  end

  def create
    @song = current_user.songs.new(song_params)
    if @song.save
    redirect_to song_path(@song)

else
    render :new
    end

end


  def edit
  end

  def update
    if @song.update(song_params)
        redirect_to song_path(@song)
    else 
        render :edit
    end
end

def set_song
  @song = current_user.songs.find(params[:id])
  
end

def song_params
  params.require(:song).permit(:title, :artist, :genre)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav>
  <%if user_signed_in?%>
  <li><%= link_to "sign Out", destroy_user_session_path, method: :delete%></li>
  
  <%else%>
  <li><%= link_to "Log In", new_user_session_path%></li>
  
  <li><%= link_to "Sign Up", new_user_registration_path%></li>
  
  <%end%>
  
  </nav>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>

   

  </body>
</html>

app/views/pages/home.html.erb
<h1>MUSE</h1>
<p>Your Ultimate Music Sharing Experience </p>

app/views/songs/edit.html.erb
<h1> Alter Song Information</h1>
<%= form_for @song do |f| %>
    <%= f.label :title%>
    <%= f.text_field :title%>
    <%= f.label :artist%>
    <%= f.text_field :artist %>
    <%= f.label :genre%>
    <%= f.text_field :genre %>
    <%= f.submit "Save" %>
    <% end %>

    

app/views/songs/index.html.erb
<h1> Library </h1>

<table>
    <tr>
        <th>Song Description</th>
    </tr>
    <% @songs.each do |song|%>
        <tr>
        <td class="data-feild"><%= song.title%></td>
        <td class="data-feild"><%= song.artist%></td>
        <td class="data-feild"><%= song.genre%></td>
        <td class="show-feild"><%= link_to 'Show', song %></td>
        
        <% if current_user.id == song.user_id %>
        <td class="show-feild"><%= link_to 'Edit', edit_song_path(song) %></td>
        <td class="show-feild"><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure of deleting the selected?' } %></td>
        <% end %>
        </tr>
    <%end%>
    

</table>
<button type="button" class="button-feild"><%= link_to 'New Song', new_song_path %></button>

app/views/songs/new.html.erb
<h1> New Song </h1>

<%= form_for Song.new do |f| %>
    <%= f.label :title%>
    <%= f.text_field :title %>
    <%= f.label :artist%>
    <%= f.text_field :artist %>
    <%= f.label :genre%>
    <%= f.text_field :genre %>
    <%= f.submit "Save" %>
    <% end %>

app/views/songs/show.html.erb
<p> <%= link_to "Back", songs_path %> </p>


<p>
<%= @song.title%>
</p>
<p>
<%= @song.artist%>
</p>
<p>
<%= @song.genre%>
</p>